# -*- coding: utf-8 -*-
"""extrapolation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WW4j9tcuLrM9KNP2_m-q6AmTsmnNQp_T
"""

import pandas as pd
import numpy as np
import json

"""# Load Full Dataset"""

with open('./full_data.json', 'r') as file:
    data = pd.read_json(json.load(file), orient='table')
 
data.pop('Units of E')
data.pop('Cloud Point')
data.pop('No');

# data = np.asarray(data)

"""# Compute Convex Hull
Compute convex hull of the datasets with resepct to the 5 design variables. We use the Delaunay triangulation [1] since it also returns the simplices from which we can check whether a point belongs to the convex hull or not. 

[1] Delaunay, Boris (1934). "Sur la sphère vide". Bulletin de l'Académie des Sciences de l'URSS, Classe des Sciences Mathématiques et Naturelles. 6: 793–800.
"""

from scipy.spatial import Delaunay
hull = Delaunay(data)

"""# Import Design/Results data"""

with open('results.json', 'r') as file:
    results = pd.read_json(file)
#print('############## result ##############\n', results)
#print('############### end ######################')
results['Extrapolation'] = ~hull.find_simplex(results.loc[:, 'Units of A':'M'])>= 0 
print('Extrapolation ratio: ', np.mean(results['Extrapolation']))

results.sort_index()